default: &default
 default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: postgresql://myacademyquest_db_user:e9mcMlEX7Ae7KkcmiRjC9IOXo9HEqW4q@dpg-d2i786re5dus73egna70-a.singapore-postgres.render.com/myacademyquest_db

development:
  <<: *default
  database: myacademyquest_development

test:
  <<: *default
  database: myacademyquest_test

production:
  <<: *default
  database: myacademyquest_production
